### ISSUE TITLE
Taille de pop au Danemark

### ISSUE THREAD

**Issue by kjean** [pbarban/publication_MT#10]
à la fin du code de formatage des données Danemark, la pop totale est  de 9,4 millions, au lieu de qqch comme 4.5 millions attendu (selon les tranches d'âge)

**Comment by pbarban** [comment]
``` r
(Denmark_data %>% 
    group_by(sexe, mode) %>% 
    summarise(sum(pop)))
```

<sup>Created on 2021-11-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by pbarban** [comment]
Il faut aussi prendre en compte le mode de transport (marche et vélo) 

``` r
(Denmark_data %>% 
    group_by(sexe, mode) %>% 
    summarise(sum(pop)))
```
