### ISSUE TITLE
error code negawatt_data.R

### ISSUE THREAD

**Issue by kjean** [pbarban/publication_MT#8]
Message retourné quand je le lance
Error in read_csv(file = "nw_data.csv", show_col_types = FALSE, col_names = c("type",  : 
  unused argument (show_col_types = FALSE)

si je change show_col_types = T ça semble marcher

**Comment by pbarban** [comment]
Je viens de tester et pour moi ça marche. On devrait verifier que l'on soit bien sur la meme version de r:
Moi je suis en: 

version 
               _                           
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          1.1                         
year           2021                        
month          08                          
day            10                          
svn rev        80725                       
language       R                           
version.string R version 4.1.1 (2021-08-10)
nickname       Kick Things

**Comment by kjean** [comment]
ok, j'ai mis à jour, ça marche chez moi
